server:
  port: 1010

spring:
  datasource:
    url: jdbc:h2:mem:oauth
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
